version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wearable_system
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wearable_net

  backend:
    build: .
    restart: always
    links:
      - db
    ports:
      - 3000:3000
    networks:
      - wearable_net
    depends_on:
      - db
    command: sh -c "npm run start:dev"

    volumes:
      - backend_data:/wearable_system

volumes:
  mysql_data:
  backend_data:


networks:
  wearable_net:
    driver: bridge